### PR TITLE
stm32l4: drop oldest bytes in case of overrun

### PR DESCRIPTION
**Pull request by badochov**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/426
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by agkaminski — COMMENTED** [review]
Last commit LGTM, will need rebase after first PR i merged

**Review by agkaminski — APPROVED** [review]
LGTM

**Comment by badochov** [comment]
@maska989 are all CIs needs met by this PR?

**Comment by maska989** [comment]
> @maska989 are all CIs needs met by this PR? I run psh test locally and encountered no issues, however maybe something comes up on your end

I checked the rest of the targets and did not encounter any errors related to this.

**Pull request merged**
