### PR TITLE
sensors/gps: increase accuracy of lat/lon with `double`/`int64_t` type

### PR DESCRIPTION
**Pull request by niewim19**
## Description

 - Using `double` variable type for calculations on latitude and longitude to not loose accuracy.
 - Using `int64_t` as transfer data type for longitude and latitude to not loose accuracy
 - Transferring latitude and longitude in nanodegrees (10^9 * [deg]). This gives worst case scenario (on equator) accuracy of 100µm/LSB which is far more that necessary. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by kemonats** [comment]
Just what position accuracy does the receiver have?

**Comment by niewim19** [comment]
> Just what position accuracy does the receiver have?

Currently implemented PA6H has measurement decimal precision of 10^-4 arc minute, translating to ~18cm on equator. However some COTS modules (ublox NEO series) can provide decimal precision of 10^-7 arc minute which translates to 0.2mm on equator.

When it comes to accuracy of currently implemented pa6h module it is stated in datasheet that accuracy (CEP) is 3m for position and 0.1 m/s for velocity.

**Review by agkaminski — APPROVED** [review]
LGTM

**Comment by kemonats** [comment]
The accuracy of the 3m position is about 16 * 10^-4 minutes of arc on the meridian. that is, the value read from the receiver is +- 16 * 10^-4 arc minutes.
I wonder what the position accuracy is with these 10^-7 arc minutes.

**Comment by niewim19** [comment]
> The accuracy of the 3m position is about 16 * 10^-4 minutes of arc on the meridian. that is, the value read from the receiver is +- 16 * 10^-4 arc minutes. I wonder what the position accuracy is with these 10^-7 arc minutes.

Currently i work with PA6H and I can tell that this 3m CEP estimate is pretty bloated :) I cant tell for the error (how far is the reported position from the true position) but speaking spread-wise it is quite easy to achieve a position spread below ~1m with just enough satelites. And if PA6H catches DGPS fix type then the full precision of returned NMEA is used as the spread is minimal - hopping on the last decimal place and giving +-15cm position changes when standing still.

The NMEA messages with 10^-7 arc minute precision gives the minimal step of about 1mm. It works for example in geodetic uses (using RTCM/RTK) where position estimation is important down to centimeters.

**Pull request merged**
