### PR TITLE
stm32-multi: Fix invalid header installation

### PR DESCRIPTION
**Pull request by anglov**
There was a conflict between rules for stm32l1 and stm32l4 header
version of stm32-multi.h. Changes unify name usage to avoid problematic
stm32-multi repeat for different components.

JIRA: ISC-105

### CODE REVIEW

**Comment by anglov** [comment]
Some more background:
When I build project, I found that stm32l1 header was installled instead of stm32l4. It's because duplication of header installation rule probably. 

To avoid that I renamed both headers. To not confuse further I renamed also binary of stm32-mult for l4 to stm32l4-multi. Before it was stm32l1-multi for l1 and stm32-multi for l4. It was not needed, but I think it will be better and less confusing that way,

**Comment by nalajcie** [comment]
I like the change, I didn't do it myself because I was afraid of disrupting some internal projects.

Needs additional changes in `phoenix-rtos-project`, otherwise LGTM.

**Comment by anglov** [comment]
> I like the change, I didn't do it myself because I was afraid of disrupting some internal projects.
> 
> Needs additional changes in `phoenix-rtos-project`, otherwise LGTM.

Need to add something more than 
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/88
(i cannot add reviewers there)

**Comment by nalajcie** [comment]
> Need to add something more than
> [phoenix-rtos/phoenix-rtos-project#88](https://github.com/phoenix-rtos/phoenix-rtos-project/pull/88)
> (i cannot add reviewers there)


Should be enough, but commit hash might change after merging this PR.

I think we can merge this now and update the other PR if needed.

**Review by nalajcie — APPROVED** [review]

**Pull request merged**
